### ISSUE TITLE
FIX #blocker: unexpected indent (alignment_model.py, line 479)

### ISSUE THREAD

**Issue by allanlaal** [joelgraff/freecad.trails#83]
trails: todays `master` tip
FreeCAD 0.20, Libs: 0.20R25220

when switching to trails Workspace:

	unexpected indent (alignment_model.py, line 479)
	Traceback (most recent call last):
	  File "/home/allan/.FreeCAD/Mod/trails/freecad/trails/init_gui.py", line 225, in Initialize
		from .design.project.commands import create_alignment_from_line
	  File "/home/allan/.FreeCAD/Mod/trails/freecad/trails/design/project/commands/create_alignment_from_line.py", line 28, in <module>
		from ...alignment import horizontal_alignment
	  File "/home/allan/.FreeCAD/Mod/trails/freecad/trails/design/alignment/horizontal_alignment.py", line 41, in <module>
		from .alignment_model import AlignmentModel

**Comment by joelgraff** [comment]
Hmmm. I’ll take a look in the next day or so.  Thanks for pointing it out.

**Comment by allanlaal** [comment]
fixed (seemingly) by replacing `freecad/trails/design/alignment/alignment_model.py` with the contents of `freecad/trails/design/alignment/alignment_model_rewrite.py`

**Comment by joelgraff** [comment]
This has been fixed.
